//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyAdminMVC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ComplainCenterEntities : DbContext
    {
        public ComplainCenterEntities()
            : base("name=ComplainCenterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<User> Users { get; set; }
        public DbSet<UserType> UserTypes { get; set; }
        public DbSet<Complain> Complains { get; set; }
        public DbSet<ComplainStatus> ComplainStatuses { get; set; }
        public DbSet<Location> Locations { get; set; }
        public DbSet<PC> PCs { get; set; }
    }
}
